name: LaTeX to PDF Conversion

on:
  push:
    branches:
      - main  # Attiva solo su commit o merge su main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone DocsSource
        uses: actions/checkout@v4
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          fetch-depth: 2
      
      - name: Clone destination repo
        uses: actions/checkout@v4
        with:
          repository: lalb03/Prova
          path: Documents
          token: ${{secrets.ACCESS_TOKEN}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install LaTeX and dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          latexmk \
          texlive \
          texlive-latex-extra \
          texlive-lang-italian

      - name: Configure Git Safe Directory for DocsSource
        run: git config --global --add safe.directory $GITHUB_WORKSPACE/DocsSource

      - name: Get changed file
        id: changed-files
        uses: tj-actions/changed-files@v45 
    

      - name: Pull latest changes
        run: |
          cd Documents
          git config --global user.name "github-action[bot]"
          git config --global user.emain "github-actions[bot]@users.noreply.github.com"
          git pull origin master

      - name: Compiling documents
        run: |
          cd Documents
          git config --global user.name "github-action[bot]"
          git config --global user.emain "github-actions[bot]@users.noreply.github.com"
          git pull
          cd ..
          echo "Deleted files: ${{ steps.changed-files.outputs.deleted_files }}"
          echo "Modified files: ${{ steps.changed-files.outputs.all_modified_files }}"
          ls
          if [[ -n "${{ steps.changed-files.outputs.deleted_files }}" ]]; then
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
              if [[ $file == *.tex ]]; then
                python delete_file.py "$file"
              fi
            done
          else
            echo "0 file have been deleted."
          fi

          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            if [[ $file == *.tex ]]; then
                python compile_tex_file.py "$file"
            fi
          done

          cd Documents
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update from GitHub Actions"
            git push
          fi
