name: LaTeX to PDF Conversion

on:
  push:
    branches:
      - main  # Attiva solo su commit o merge su main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone DocsSource
        uses: actions/checkout@v4
        with:
          repository: lalb03/Source_prova
          path: DocsSource
          token: ${{secrets.ACCESS_TOKEN}}
      
      - name: Clone destination repo
        uses: actions/checkout@v4
        with:
          repository: lalb03/Prova
          path: Documents
          token: ${{secrets.ACCESS_TOKEN}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install LaTeX and dependencies
        run: sudo apt-get update && sudo apt-get install -y latexmk texlive-full

      - name: Pull latest changes
        run: |
          cd Documents
          git config --global user.name "github-action[bot]"
          git config --global user.emain "github-actions[bot]@users.noreply.github.com"
          git pull

      - name: Run python script
        run: python main.py
          

      - name: Add, commit and push changes
        run: |
          cd Documents
          git add .
          git commit -m "Automated update from GitHub Actions"
          git push origin main
